import os
from dotenv import load_dotenv

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
CHROMA_DB_PATH = "./chroma_db"
MEDIA_STORAGE_PATH = os.getenv("MEDIA_STORAGE_PATH", "./data/media")
EMBEDDING_MODEL = "gemini-embedding-2-preview"
EMBEDDING_DIMENSIONS = 768  # Matryoshka truncation — can bump to 1536 later
MEDIA_EMBED_MAX_BYTES = int(os.getenv("MEDIA_EMBED_MAX_BYTES", str(20 * 1024 * 1024)))
SEMANTIC_HALF_LIFE_DAYS = float(os.getenv("SEMANTIC_HALF_LIFE_DAYS", "365"))
EPISODIC_HALF_LIFE_DAYS = float(os.getenv("EPISODIC_HALF_LIFE_DAYS", "30"))
PROCEDURAL_HALF_LIFE_DAYS = float(os.getenv("PROCEDURAL_HALF_LIFE_DAYS", "180"))
IMPORTANCE_FLOOR_THRESHOLD = float(os.getenv("IMPORTANCE_FLOOR_THRESHOLD", "0.8"))
IMPORTANCE_FLOOR_MULTIPLIER = float(os.getenv("IMPORTANCE_FLOOR_MULTIPLIER", "3.0"))
ACCESS_NORMALIZATION_CONSTANT = float(os.getenv("ACCESS_NORMALIZATION_CONSTANT", "50"))
SEMANTIC_PRUNE_THRESHOLD = float(os.getenv("SEMANTIC_PRUNE_THRESHOLD", "0.1"))
SEMANTIC_FADE_THRESHOLD = float(os.getenv("SEMANTIC_FADE_THRESHOLD", "0.2"))
EPISODIC_PRUNE_THRESHOLD = float(os.getenv("EPISODIC_PRUNE_THRESHOLD", "0.2"))
EPISODIC_FADE_THRESHOLD = float(os.getenv("EPISODIC_FADE_THRESHOLD", "0.35"))
PROCEDURAL_PRUNE_THRESHOLD = float(os.getenv("PROCEDURAL_PRUNE_THRESHOLD", "0.15"))
PROCEDURAL_FADE_THRESHOLD = float(os.getenv("PROCEDURAL_FADE_THRESHOLD", "0.3"))
SEMANTIC_DUPLICATE_THRESHOLD = float(os.getenv("SEMANTIC_DUPLICATE_THRESHOLD", "0.95"))
FADE_FACTOR = float(os.getenv("FADE_FACTOR", "0.5"))
FADE_FLOOR = float(os.getenv("FADE_FLOOR", "0.01"))
PROCEDURAL_LOW_PERF_WILSON_THRESHOLD = float(
    os.getenv("PROCEDURAL_LOW_PERF_WILSON_THRESHOLD", "0.1")
)
PROCEDURAL_LOW_PERF_MIN_OUTCOMES = int(os.getenv("PROCEDURAL_LOW_PERF_MIN_OUTCOMES", "10"))
